version: "3.9"

services:
  db:
    image: postgres:16
    container_name: controller_db
    environment:
      POSTGRES_USER: controller_user
      POSTGRES_PASSWORD: controller_pass
      POSTGRES_DB: controller
    ports:
      - "5435:5432" # usamos puerto diferente para no chocar con tu postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: controller_backend
    environment:
      DATABASE_URL: postgres://controller_user:controller_pass@db:5432/controller
      JWT_SECRET: super_secret_key
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: controller_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  adminer:
    image: adminer
    container_name: controller_adminer
    ports:
      - "8085:8080"
    depends_on:
      - db

volumes:
  db_data:
