version: "3.7"

services:
  traefik:
    image: traefik:latest
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  backend:
    image: ***/controller_backend:latest
    restart: always
    expose:
      - "3000"  # Cambia al puerto que usa tu backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.${DOMAIN_NAME}`)"
      - "traefik.http.routers.backend.entrypoints=web,websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=mytlschallenge"
      - "traefik.http.middlewares.backend-headers.headers.SSLRedirect=true"
      - "traefik.http.middlewares.backend-headers.headers.STSSeconds=31536000"
      - "traefik.http.middlewares.backend-headers.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.backend-headers.headers.contentTypeNosniff=true"
      - "traefik.http.routers.backend.middlewares=backend-headers@docker"

  frontend:
    image: ***/controller_frontend:latest
    restart: always
    expose:
      - "3000"  # Cambia al puerto que usa tu frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.${DOMAIN_NAME}`)"
      - "traefik.http.routers.frontend.entrypoints=web,websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=mytlschallenge"
      - "traefik.http.middlewares.frontend-headers.headers.SSLRedirect=true"
      - "traefik.http.middlewares.frontend-headers.headers.STSSeconds=31536000"
      - "traefik.http.middlewares.frontend-headers.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.frontend-headers.headers.contentTypeNosniff=true"
      - "traefik.http.routers.frontend.middlewares=frontend-headers@docker"

volumes:
  traefik_data:
    external: true
