version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    image: hwperu/controller_backend:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${E_PORT}
    depends_on:
      - db
    networks:
      - app_network
      - traefik_public
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controller-backend.rule=Host(`backend.hwperu.com`)"
      - "traefik.http.routers.controller-backend.entrypoints=websecure"
      - "traefik.http.routers.controller-backend.tls.certresolver=le"
      - "traefik.http.services.controller-backend.loadbalancer.server.port=${BACKEND_PORT}"
      - "traefik.docker.network=traefik_public"

  frontend:
    image: hwperu/controller_frontend:latest
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - app_network
      - traefik_public
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controller-frontend.rule=Host(`frontend.hwperu.com`)"
      - "traefik.http.routers.controller-frontend.entrypoints=websecure"
      - "traefik.http.routers.controller-frontend.tls.certresolver=le"
      - "traefik.http.services.controller-frontend.loadbalancer.server.port=${FRONTEND_PORT}"
      - "traefik.docker.network=traefik_public"

  adminer:
    image: adminer:latest
    networks:
      - app_network
      - traefik_public
    ports:
      - "${ADMINER_HOST_PORT}:${ADMINER_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controller-adminer.rule=Host(`admin.hwperu.com`)"
      - "traefik.http.routers.controller-adminer.entrypoints=websecure"
      - "traefik.http.routers.controller-adminer.tls.certresolver=le"
      - "traefik.http.services.controller-adminer.loadbalancer.server.port=${ADMINER_PORT}"
      - "traefik.docker.network=traefik_public"

volumes:
  db_data:

networks:
  app_network:
    external: true
  traefik_public:
    external: true
