version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Usuario que se creará automáticamente
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Contraseña del usuario
      POSTGRES_DB: ${POSTGRES_DB} # Base de datos que se creará automáticamente
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    image: hwperu/controller_backend:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 4000
    depends_on:
      - db
    # Espera hasta que Postgres esté listo antes de iniciar NestJS
    command: sh -c "apk add --no-cache dockerize && dockerize -wait tcp://db:5432 -timeout 60s && node dist/main.js"
    networks:
      - app_network
      - traefik_public
    ports:
      - 4000:4000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controller-backend.rule=Host(`backend.hwperu.com`)"
      - "traefik.http.routers.controller-backend.entrypoints=websecure"
      - "traefik.http.routers.controller-backend.tls.certresolver=le"
      - "traefik.http.services.controller-backend.loadbalancer.server.port=${BACKEND_PORT}"
      - "traefik.docker.network=traefik_public"

  frontend:
    image: hwperu/controller_frontend:latest
    environment:
      NEXT_PUBLIC_API_URL: https://backend.hwperu.com
    depends_on:
      - backend
    networks:
      - app_network
      - traefik_public
    ports:
      - 2000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controller-frontend.rule=Host(`frontend.hwperu.com`)"
      - "traefik.http.routers.controller-frontend.entrypoints=websecure"
      - "traefik.http.routers.controller-frontend.tls.certresolver=le"
      - "traefik.http.services.controller-frontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_public"

  adminer:
    image: adminer:latest
    networks:
      - app_network
      - traefik_public
    ports:
      - 8082:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controller-adminer.rule=Host(`admin.hwperu.com`)"
      - "traefik.http.routers.controller-adminer.entrypoints=websecure"
      - "traefik.http.routers.controller-adminer.tls.certresolver=le"
      - "traefik.http.services.controller-adminer.loadbalancer.server.port=8082"
      - "traefik.docker.network=traefik_public"

volumes:
  db_data:

networks:
  app_network:
    external: true
  traefik_public:
    external: true
